services:
  app:
    build: .
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=random_dev
    ports:
      - 4000:4000
    volumes:
      - .:/opt/app
      - /opt/app/deps
      - /opt/app/_build
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

volumes:
  db: {}
